// Package docsguard — guardián de documentación del repo Vulpo (ADR-011):
// catálogo de tools citado en docs == catálogo real; pisos de versión ==
// manifest; cero español funcional (con allowlist de literales justificados);
// tools.md generado fresco contra el registro.
//
// Set escaneado: docs/**/*.md, docs/reference/tools.md, agent-kit/skills/*/SKILL.md,
// README.md y server/internal/mcp/help.txt — nunca código (los comentarios ES
// de extension/ y dev-harness son deuda documentada, no docs de usuario).
package docsguard

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"vulpo/server/internal/mcp"
	"vulpo/server/internal/odooregistry"
)

// extraDirEnv: hook para la negativa anti-vacuo del gate (P6-neg): escanea un
// dir adicional con las mismas reglas. Vacío en uso normal.
const extraDirEnv = "DOCSGUARD_EXTRA_DIR"

// scannedSet: rutas relativas a la raíz del repo que se escanean.
func scannedSet(root string) ([]string, error) {
	var files []string
	docs := filepath.Join(root, "docs")
	err := filepath.WalkDir(docs, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(p, ".md") {
			return nil
		}
		files = append(files, p)
		return nil
	})
	if err != nil {
		return nil, err
	}
	skills, err := filepath.Glob(filepath.Join(root, "agent-kit", "skills", "*", "SKILL.md"))
	if err != nil {
		return nil, err
	}
	files = append(files, skills...)
	files = append(files, filepath.Join(root, "README.md"), filepath.Join(root, "server", "internal", "mcp", "help.txt"))
	sort.Strings(files)
	return files, nil
}

// buildCatalog: catálogo real de tools (21 vlp_ + 12 odoo, fb-022) sin server
// en marcha.
// V1: RegisterAllTools solo construye closures — el hub nil no se dereferencea
// en registro; el registry de Odoo se construye real (odooregistry.New).
func buildCatalog() ([]mcp.Tool, error) {
	ms := mcp.New(nil)
	mcp.RegisterAllTools(ms, nil, "", odooregistry.New())
	return ms.ListTools(), nil
}

// catalogSet: set de nombres de tool del catálogo real.
func catalogNames(tools []mcp.Tool) map[string]bool {
	out := map[string]bool{}
	for _, t := range tools {
		out[t.Name] = true
	}
	return out
}

// versionFloorFromManifest: lee version de extension/manifest.json.
func versionFloorFromManifest(root string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "extension", "manifest.json"))
	if err != nil {
		return "", err
	}
	var m struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(raw, &m); err != nil {
		return "", err
	}
	return m.Version, nil
}

// RenderToolsReference: render determinista del catálogo (familia vlp_* y
// familia odoo, orden alfabético; Description verbatim; properties/required).
func RenderToolsReference(tools []mcp.Tool) string {
	var vlp, odoo []mcp.Tool
	for _, t := range tools {
		if strings.HasPrefix(t.Name, "vlp_") {
			vlp = append(vlp, t)
		} else {
			odoo = append(odoo, t)
		}
	}
	sort.Slice(vlp, func(i, j int) bool { return vlp[i].Name < vlp[j].Name })
	sort.Slice(odoo, func(i, j int) bool { return odoo[i].Name < odoo[j].Name })

	var b strings.Builder
	b.WriteString("<!-- GENERATED by cmd/gen-docs — do not edit; regenerate: (cd server && go run ./cmd/gen-docs) -->\n\n")
	b.WriteString("# Tools reference\n\n")
	b.WriteString("Verbatim from the server's tool registry (33 tools: 21 `vlp_*` + 12 Odoo).\n\n")
	b.WriteString("## Browser tools (vlp_*)\n\n")
	for _, t := range vlp {
		renderTool(&b, t)
	}
	b.WriteString("## Odoo tools (mcp.odoo parity)\n\n")
	for _, t := range odoo {
		renderTool(&b, t)
	}
	return b.String()
}

func renderTool(b *strings.Builder, t mcp.Tool) {
	fmt.Fprintf(b, "### `%s`\n\n%s\n\n", t.Name, strings.TrimSpace(t.Description))
	props, _ := t.InputSchema["properties"].(map[string]any)
	if len(props) == 0 {
		b.WriteString("_No parameters._\n\n")
		return
	}
	names := make([]string, 0, len(props))
	for k := range props {
		names = append(names, k)
	}
	sort.Strings(names)
	req, _ := t.InputSchema["required"].([]any)
	reqSet := map[string]bool{}
	for _, r := range req {
		if s, ok := r.(string); ok {
			reqSet[s] = true
		}
	}
	b.WriteString("| Param | Type | Required |\n|---|---|---|\n")
	for _, n := range names {
		p, _ := props[n].(map[string]any)
		ptype, _ := p["type"].(string)
		mark := ""
		if reqSet[n] {
			mark = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", n, ptype, mark)
	}
	b.WriteString("\n")
}

// allowedSpanish: allowlist codificada (sufijo de ruta → líneas 1-based con
// literales de UI Odoo y código JS justificados; verificado contra el árbol
// real 2026-09-21).
var allowedSpanish = map[string][]int{
	"agent-kit/skills/vulpo-odoo-web/SKILL.md":       {270, 271, 276, 341, 342},
	"agent-kit/skills/vulpo-web-navigation/SKILL.md": {249, 250, 380},
	// fb-022: nota user-only del plan/build (popup de la extensión).
	"agent-kit/skills/vulpo/SKILL.md": {84},
}
